//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facturation_v05.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacturationBDD_v02Entities : DbContext
    {
        public FacturationBDD_v02Entities()
            : base("name=FacturationBDD_v02Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Client_details> Client_details { get; set; }
        public virtual DbSet<Contrat> Contrat { get; set; }
        public virtual DbSet<Facture> Facture { get; set; }
        public virtual DbSet<Facture_details> Facture_details { get; set; }
        public virtual DbSet<Final_client> Final_client { get; set; }
    }
}
