//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facturation_v05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_details
    {
        public int client_detail_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<bool> client_mediator { get; set; }
        public Nullable<int> final_client_id { get; set; }
        public string final_client_nom { get; set; }
        public string client_adresse { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Final_client Final_client { get; set; }
    }
}
