//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facturation_v05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrat()
        {
            this.Facture = new HashSet<Facture>();
        }
    
        public int contrat_id { get; set; }
        public string description { get; set; }
        public Nullable<decimal> prix_unitaire { get; set; }
        public Nullable<int> final_client_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public string ref_contrat { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Final_client Final_client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture> Facture { get; set; }
    }
}
