//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facturation_v05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture_details
    {
        public int fact_detail_id { get; set; }
        public string num_fact { get; set; }
        public Nullable<int> fact_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<decimal> quantite { get; set; }
        public Nullable<System.DateTime> date_envoie { get; set; }
        public Nullable<decimal> prix_unitaire { get; set; }
        public Nullable<System.DateTime> mois { get; set; }
        public string description { get; set; }
        public Nullable<int> tva { get; set; }
        public Nullable<decimal> total_ht { get; set; }
        public Nullable<decimal> total_ttc { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Facture Facture { get; set; }
    }
}
